spring.application.name=github-repo-popularity-scorer
server.port=8081

popularity.weights.stars=0.6
popularity.weights.forks=0.3
popularity.weights.recency=0.1
popularity.weights.recency-max-days=365

github.api.base-url=https://api.github.com
github.api.search-repo-path=/search/repositories
github.api.sort=stars
github.api.order=desc
github.api.per-page=30

springdoc.swagger-ui.path=/swagger-ui.html